"""Browser (web-session) API façade.

Historically all SSO-only endpoints lived in one large module. The implementation is now split
into smaller domain modules, and this file re-exports the public API to keep import paths stable.
"""

from __future__ import annotations

from .availability import (
    AllocateResult,
    ClusterBasicInfo,
    FullFreeNodeCount,
    GPUAvailability,
    GroupPreemptibility,
    GroupStatus,
    LOW_PRIORITY_THRESHOLD,
    NodeDimension,
    NodeTask,
    PreemptibleNode,
    PreemptibleTask,
    ProjectBudget,
    TaskDimension,
    TaskNode,
    compute_allocate_overview,
    find_best_compute_group_accurate,
    get_accurate_gpu_availability,
    get_cluster_basic_info,
    get_full_free_node_counts,
    list_compute_groups,
    list_node_dimension,
    list_task_dimension,
)
from .jobs import (
    InstanceInfo,
    JobInfo,
    create_job,
    fetch_job_logs,
    get_current_user,
    get_job_detail,
    get_train_job_workdir,
    get_train_resource_prices,
    list_job_events,
    list_job_instances,
    list_job_users,
    list_jobs,
    resolve_train_resource_spec_price,
    stop_job,
)
from .notebooks import (
    ImageInfo,
    NotebookFailedError,
    create_notebook,
    get_notebook_detail,
    get_notebook_schedule,
    get_resource_prices,
    list_images,
    list_notebook_compute_groups,
    start_notebook,
    stop_notebook,
    wait_for_notebook_running,
)
from .playwright_notebooks import run_command_in_notebook
from .images import (
    CustomImageInfo,
    create_image,
    delete_image,
    get_image_detail,
    list_images_by_source,
    list_private_images,
    save_notebook_as_image,
    wait_for_image_ready,
)
from .projects import (
    ProjectInfo,
    check_scheduling_health,
    list_projects,
    select_project,
)

__all__ = [
    # Jobs / users / instances / logs
    "InstanceInfo",
    "JobInfo",
    "create_job",
    "fetch_job_logs",
    "get_current_user",
    "get_job_detail",
    "get_train_job_workdir",
    "get_train_resource_prices",
    "list_job_events",
    "list_job_instances",
    "list_job_users",
    "list_jobs",
    "resolve_train_resource_spec_price",
    "stop_job",
    # Availability
    "AllocateResult",
    "FullFreeNodeCount",
    "GPUAvailability",
    "GroupPreemptibility",
    "GroupStatus",
    "LOW_PRIORITY_THRESHOLD",
    "PreemptibleNode",
    "PreemptibleTask",
    "ProjectBudget",
    "compute_allocate_overview",
    "find_best_compute_group_accurate",
    "get_accurate_gpu_availability",
    "get_full_free_node_counts",
    "list_compute_groups",
    # Cluster metrics
    "ClusterBasicInfo",
    "NodeDimension",
    "NodeTask",
    "TaskDimension",
    "TaskNode",
    "get_cluster_basic_info",
    "list_node_dimension",
    "list_task_dimension",
    # Projects
    "ProjectInfo",
    "check_scheduling_health",
    "list_projects",
    "select_project",
    # Images
    "CustomImageInfo",
    "create_image",
    "delete_image",
    "get_image_detail",
    "list_images_by_source",
    "list_private_images",
    "save_notebook_as_image",
    "wait_for_image_ready",
    # Notebooks
    "ImageInfo",
    "NotebookFailedError",
    "create_notebook",
    "get_notebook_detail",
    "get_notebook_schedule",
    "get_resource_prices",
    "list_images",
    "list_notebook_compute_groups",
    "run_command_in_notebook",
    "start_notebook",
    "stop_notebook",
    "wait_for_notebook_running",
]
